openapi: 3.0.1
info:
  title: Operational Data API
  version: '0.1'
paths:
  /visits/{shipReportingSystemEntryPortCode}/{shipImoNumber}/{shipStayReferenceNumber}:
    get:
      tags:
        - Operational Data API
      summary: Request Operational Data
      description: >-
        This endpoint can be used to request operational data from a ships visit
      operationId: submit
      parameters:
        - name: shipReportingSystemEntryPortCode
          in: path
          required: true
          schema:
            type: string
        - name: shipImoNumber
          in: path
          required: true
          schema:
            type: string
        - name: shipStayReferenceNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OperationalData'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
components:
  schemas:
    OperationalData:
      title: OperationalData
      type: object
      properties:
        shipReportingSystemEntryPortCode:
          type: string
          nullable: true
        shipImoNumber:
          type: string
          nullable: true
        shipStayReferenceNumber:
          type: string
          nullable: true
        portArrival:
          $ref: '#/components/schemas/PortArrival'
        berthVisits:
          type: array
          items:
            $ref: '#/components/schemas/BerthVisit'
        portDeparture:
          $ref: '#/components/schemas/PortDeparture'
    PortArrival:
      title: PortArrival
      allOf: 
        - $ref: '#/components/schemas/ArrivalTimestamps'
        - type: object
          properties:
            pilotBoardingPlaceName:
              type: string
              nullable: true
    BerthVisit:
      title: BerthVisit
      allOf: 
        - $ref: '#/components/schemas/ArrivalTimestamps'
        - $ref: '#/components/schemas/DepartureTimestamps'
        - type: object
          properties:
            berthName:
              type: string
              nullable: true
            gln:
              type: string
              nullable: true
    PortDeparture:
      title: PortDeparture
      allOf: 
        - $ref: '#/components/schemas/DepartureTimestamps'
        - type: object
          properties:
            berthName:
              type: string
              nullable: true
            gln:
              type: string
              nullable: true
    ArrivalTimestamps:
      title: ArrivalTimestamps
      type: object
      properties:
        plannedTimeOfArrival:
          type: string
          format: date-time
          nullable: true
        actualTimeOfArrival:
          type: string
          format: date-time
          nullable: true
    DepartureTimestamps:
      title: DepartureTimestamps
      type: object
      properties:
        plannedTimeOfDeparture:
          type: string
          format: date-time
          nullable: true
        actualTimeOfDeparture:
          type: string
          format: date-time
          nullable: true
