openapi: 3.0.1
info:
  title: Operational Data API
  version: '1.0'
paths:
  /port-arrival/{shipReportingSystemEntryPortCode}/{shipImoNumber}/{shipStayReferenceNumber}:
    get:
      tags:
        - Operational Data API
      summary: Request Operational Data for Port Arrival
      operationId: port-arrival
      parameters:
        - name: shipReportingSystemEntryPortCode
          in: path
          required: true
          schema:
            type: string
        - name: shipImoNumber
          in: path
          required: true
          schema:
            type: string
        - name: shipStayReferenceNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortArrival'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /port-departure/{shipReportingSystemEntryPortCode}/{shipImoNumber}/{shipStayReferenceNumber}:
    get:
      tags:
        - Operational Data API
      summary: Request Operational Data voor Port Departure
      operationId: port-departure
      parameters:
        - name: shipReportingSystemEntryPortCode
          in: path
          required: true
          schema:
            type: string
        - name: shipImoNumber
          in: path
          required: true
          schema:
            type: string
        - name: shipStayReferenceNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortDeparture'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
components:
  schemas:
    PortArrivalDeparture:
      title: OperationalData
      type: object
      properties:
        shipReportingSystemEntryPortCode:
          type: string
          nullable: true
        shipImoNumber:
          type: string
          nullable: true
        shipStayReferenceNumber:
          type: string
          nullable: true
    PortArrival:
      title: PortArrival
      allOf: 
        - $ref: '#/components/schemas/PortArrivalDeparture'
        - type: object
          properties:
            pilotBoardingPlaceName:
              type: string
              nullable: true
            plannedTimeOfArrival:
              type: string
              format: date-time
              nullable: true
    PortDeparture:
      title: PortDeparture
      allOf: 
        - $ref: '#/components/schemas/PortArrivalDeparture'
        - type: object
          properties:
            berthName:
              type: string
              nullable: true
            berthGln:
              type: string
              nullable: true
            plannedTimeOfDeparture:
              type: string
              format: date-time
              nullable: true
