// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://swagger.yaml` | (string & {});
};

/**
 * A location with a global location number (GLN) and a name.
 */
export type Location = {
    /**
     * Global location number (GLN)
     */
    gln: string;
    /**
     * Name of the location (terminal or berth)
     */
    name: string;
    /**
     * Short name of the Location
     */
    shortName?: string;
};

export type Terminal = Location & {
    geoCoordinate: Coordinate;
    /**
     * Port facility number of the terminal
     */
    portFacilityNumber?: string;
    /**
     * Type of the terminal
     */
    terminalType: 'Unknown' | 'BulkTerminal' | 'ContainerTerminal' | 'TankerTerminal' | 'FerryTerminal' | 'PassengerTerminal' | 'RoRoTerminal' | 'ServiceHarbour' | 'ServiceRepair' | 'Shipyard';
};

export type Berth = Location & {
    /**
     * The berth type
     */
    berthType: 'Unknown' | 'None' | 'Anchor Berth' | 'Fender or Breasting Dolphin' | 'Mole' | 'Multi Buoy Mooring (MBM) Berth' | 'Open Face Wharf' | 'Pier (Jetty)' | 'Quay' | 'Ramp' | 'Slipway' | 'Solid Face Wharf' | 'Tie-Up Wall' | 'Wharf';
    /**
     * UN/LO code
     */
    unloCode: string;
    geoCoordinates: ArrayOfCoordinate;
};

/**
 * A berth position
 */
export type BerthPosition = {
    /**
     * Global location number (GLN) with extension
     */
    glnWithExt: string;
    /**
     * Name of the berth position
     */
    name: string;
    /**
     * The berth position type
     */
    type: 'Unknown' | 'Not Applicable' | 'Loading Arm / Manifold Number' | 'Ramp Number' | 'Bollard Number' | 'Meter Mark Number';
    geoCoordinate: Coordinate;
};

/**
 * A coordinate.
 */
export type Coordinate = {
    /**
     * Latitude part of coordinate
     */
    latitude: number;
    /**
     * Longitude part of coordinate
     */
    longitude: number;
};

/**
 * A terminal with berths
 */
export type TerminalWithBerths = Terminal & {
    berths: ArrayOfLocation;
};

/**
 * A terminal with berth and berth positions
 */
export type TerminalWithBerthsAndPositions = Terminal & {
    berths: ArrayOfBerthWithPositions;
};

/**
 * A berth with berth positions
 */
export type BerthWithPositions = Berth & {
    positions?: ArrayOfBerthPosition;
};

export type ArrayOfCoordinate = Array<Coordinate>;

export type ArrayOfLocation = Array<Location>;

export type ArrayOfBerthWithPositions = Array<BerthWithPositions>;

export type ArrayOfBerthPosition = Array<BerthPosition>;

export type ArrayOfTerminalWithBerthsAndPositions = Array<TerminalWithBerthsAndPositions>;

export type TerminalsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/terminals';
};

export type TerminalsResponses = {
    /**
     * Success
     */
    200: ArrayOfLocation;
};

export type TerminalsResponse = TerminalsResponses[keyof TerminalsResponses];

export type TerminalData = {
    body?: never;
    path: {
        gln: string;
    };
    query?: never;
    url: '/terminals/{gln}';
};

export type TerminalErrors = {
    /**
     * Terminal not found
     */
    404: unknown;
};

export type TerminalResponses = {
    /**
     * Success
     */
    200: TerminalWithBerths;
};

export type TerminalResponse = TerminalResponses[keyof TerminalResponses];

export type BerthData = {
    body?: never;
    path: {
        gln: string;
    };
    query?: never;
    url: '/berths/{gln}';
};

export type BerthErrors = {
    /**
     * Berth not found
     */
    404: unknown;
};

export type BerthResponses = {
    /**
     * Success
     */
    200: BerthWithPositions;
};

export type BerthResponse = BerthResponses[keyof BerthResponses];

export type FetchAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fetchAll';
};

export type FetchAllErrors = {
    /**
     * No terminals and berths found
     */
    404: unknown;
};

export type FetchAllResponses = {
    /**
     * Success
     */
    200: ArrayOfTerminalWithBerthsAndPositions;
};

export type FetchAllResponse = FetchAllResponses[keyof FetchAllResponses];
